<a href="https://colab.research.google.com/github/casanchez25/Diputados_8-7_Tribunal_Electoral/blob/main/Estudio_Diputados_y_Representantes_8_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# REVISIÓN DE INFORMACIÓN DE VOTACIONES POR CIRCUITO 8-9

Primero importamos las librerías necesarias y el dataset inicial. Estaremos revisando primero los ganadores de Diputados y sus estadísticas

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_excel('/content/drive/MyDrive/ESTADISTICA DIPUTADO - REPRESENTANTE.xlsx')

## **DIPUTADO**

### Acomodando el candidato con su partido y votos obtenidos

Primero verificaremos si la columna de PARTIDO está bien tomada (fue hecha en Excel). Para ello acomodaremos y utilizaremos la función MELT de pandas

In [ ]:
df.head(5)

,Distrito,Circuito,AÑO,Corregimiento,Centro,PARTIDO,Candidato,MESA,ELECTORES,EMITIDOS,...,ALIANZA,CELESTE,VERDE,CHOCOLATE,PL,UP,VMP,TOTALES,% MESA POR ESCUELA,% DE PARTICIPACION
0,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,CHOCOLATE,Alexis Jimenez Oliva,3606.0,498.0,256.0,...,NaN,NaN,NaN,4.0,NaN,NaN,NaN,4,0.007421,0.514056
1,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,ALIANZA,Algis Teovaldo Torres Perez,3606.0,498.0,256.0,...,8.0,NaN,NaN,NaN,NaN,NaN,NaN,8,0.014842,0.514056
2,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,P.R.D.,Alina Ines Gonzalez Cordoba De Cedeño,3606.0,498.0,256.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58,0.107607,0.514056
3,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,VERDE,Antonio Dimitri Alexopulos Castillo,3606.0,498.0,256.0,...,NaN,NaN,2.0,NaN,NaN,NaN,NaN,2,0.003711,0.514056
4,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,C.D.,Ariel Ulises Vallarino Aparicio,3606.0,498.0,256.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44,0.081633,0.514056

In [ ]:
df['Candidato']=df['Candidato'].apply(lambda x: str.upper(x))

Obtenemos el listado de columnas para luego depurar los números requeridos

In [ ]:
cols=df.columns.to_list() 
cols

['Distrito',
 'Circuito',
 'AÑO',
 'Corregimiento',
 'Centro',
 'PARTIDO',
 'Candidato',
 'MESA',
 'ELECTORES',
 'EMITIDOS',
 'VALIDOS',
 'BLANCOS',
 'NULOS',
 'P.R.D.',
 'POPULAR',
 'MOLIRENA',
 'PAN',
 'C.D.',
 'F.A.D.',
 'ALIANZA',
 'CELESTE',
 'VERDE',
 'CHOCOLATE',
 'PL',
 'UP',
 'VMP',
 'TOTALES',
 '% MESA POR ESCUELA',
 '% DE PARTICIPACION']

In [ ]:
df.fillna(0,inplace=True)
df1=df[cols[13:26]]

df1['Candidato']=df['Candidato']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
df_partidos=df.groupby(['AÑO','Corregimiento','Centro','MESA'])[cols[13:26]].max()

In [ ]:
df_partidos.reset_index(inplace=True)

In [ ]:
df_partidos=df_partidos.melt(id_vars=['AÑO','Corregimiento','Centro','MESA'],var_name='Partido',value_name='Cantidad')
df_partidos.to_csv('/content/drive/MyDrive/Votaciones - Debug/vot_partidos_dip.csv', index_label='index')

In [ ]:
df1

,P.R.D.,POPULAR,MOLIRENA,PAN,C.D.,F.A.D.,ALIANZA,CELESTE,VERDE,CHOCOLATE,PL,UP,VMP,Candidato
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,ALEXIS JIMENEZ OLIVA
1,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,ALGIS TEOVALDO TORRES PEREZ
2,58.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ALINA INES GONZALEZ CORDOBA DE CEDEÑO
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,ANTONIO DIMITRI ALEXOPULOS CASTILLO
4,0.0,0.0,0.0,0.0,44.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,ARIEL ULISES VALLARINO APARICIO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15822,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,RUBEN QUINTERO
15823,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,SILBESTRA M. FLORES SILVIA
15824,0.0,0.0,0.0,0.0,79.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,VIDAL GARCIA UREÑA
15825,0.0,0.0,0.0,0.0,94.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,WIGBERTO QUINTERO
15826,44.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,YASSIR ABOOBEKER PURCAIT SABORIO

Realizaremos un MELT de el candidato con su partido, para que nos quede una columna de partidos con los votos recibidos de cada uno

In [ ]:
def partido(df1):
  df1['key']=df1.index
  df1=df1.melt(id_vars=['Candidato','key'])
  df1=df1[df1['value']>0]
  df1.set_index('key', inplace=True)
  df1=df1.sort_index(ascending=True)
  return df1

In [ ]:
df1= partido(df1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
df1

                                   Candidato   variable  value
key
0                       ALEXIS JIMENEZ OLIVA  CHOCOLATE    4.0
1                ALGIS TEOVALDO TORRES PEREZ    ALIANZA    8.0
2      ALINA INES GONZALEZ CORDOBA DE CEDEÑO     P.R.D.   58.0
3        ANTONIO DIMITRI ALEXOPULOS CASTILLO      VERDE    2.0
4            ARIEL ULISES VALLARINO APARICIO       C.D.   44.0
...                                      ...        ...    ...
15822                         RUBEN QUINTERO         UP    7.0
15823             SILBESTRA M. FLORES SILVIA        VMP    1.0
15824                     VIDAL GARCIA UREÑA       C.D.   79.0
15825                      WIGBERTO QUINTERO       C.D.   94.0
15826       YASSIR ABOOBEKER PURCAIT SABORIO     P.R.D.   44.0

[15140 rows x 3 columns]

Ahora uniremos los dataframes

In [ ]:
dfn=df.join(df1, lsuffix='l')

In [ ]:
dfn.head(10)

,Distrito,Circuito,AÑO,Corregimiento,Centro,PARTIDO,Candidatol,MESA,ELECTORES,EMITIDOS,...,CHOCOLATE,PL,UP,VMP,TOTALES,% MESA POR ESCUELA,% DE PARTICIPACION,Candidato,variable,value
0,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,CHOCOLATE,ALEXIS JIMENEZ OLIVA,3606.0,498.0,256.0,...,4.0,0.0,0.0,0.0,4,0.007421,0.514056,ALEXIS JIMENEZ OLIVA,CHOCOLATE,4.0
1,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,ALIANZA,ALGIS TEOVALDO TORRES PEREZ,3606.0,498.0,256.0,...,0.0,0.0,0.0,0.0,8,0.014842,0.514056,ALGIS TEOVALDO TORRES PEREZ,ALIANZA,8.0
2,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,P.R.D.,ALINA INES GONZALEZ CORDOBA DE CEDEÑO,3606.0,498.0,256.0,...,0.0,0.0,0.0,0.0,58,0.107607,0.514056,ALINA INES GONZALEZ CORDOBA DE CEDEÑO,P.R.D.,58.0
3,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,VERDE,ANTONIO DIMITRI ALEXOPULOS CASTILLO,3606.0,498.0,256.0,...,0.0,0.0,0.0,0.0,2,0.003711,0.514056,ANTONIO DIMITRI ALEXOPULOS CASTILLO,VERDE,2.0
4,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,C.D.,ARIEL ULISES VALLARINO APARICIO,3606.0,498.0,256.0,...,0.0,0.0,0.0,0.0,44,0.081633,0.514056,ARIEL ULISES VALLARINO APARICIO,C.D.,44.0
5,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,P.A.N.,CEFERINO RODRIGUEZ ESPINOSA,3606.0,498.0,256.0,...,0.0,0.0,0.0,0.0,49,0.090909,0.514056,CEFERINO RODRIGUEZ ESPINOSA,PAN,42.0
5,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,P.A.N.,CEFERINO RODRIGUEZ ESPINOSA,3606.0,498.0,256.0,...,0.0,0.0,0.0,0.0,49,0.090909,0.514056,CEFERINO RODRIGUEZ ESPINOSA,POPULAR,7.0
6,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,F.A.D.,CESAR VASQUEZ RICO,3606.0,498.0,256.0,...,0.0,0.0,0.0,0.0,4,0.007421,0.514056,CESAR VASQUEZ RICO,F.A.D.,4.0
7,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,P.A.N.,DAVID VICTORIANO GUARDIA QUIJADA,3606.0,498.0,256.0,...,0.0,0.0,0.0,0.0,40,0.074212,0.514056,DAVID VICTORIANO GUARDIA QUIJADA,PAN,40.0
8,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,POPULAR,ERNESTO GIL VEGA REYES,3606.0,498.0,256.0,...,0.0,0.0,0.0,0.0,7,0.012987,0.514056,ERNESTO GIL VEGA REYES,POPULAR,7.0

In [ ]:
df1.head(10)

                                 Candidato   variable  value
key
0                     ALEXIS JIMENEZ OLIVA  CHOCOLATE    4.0
1              ALGIS TEOVALDO TORRES PEREZ    ALIANZA    8.0
2    ALINA INES GONZALEZ CORDOBA DE CEDEÑO     P.R.D.   58.0
3      ANTONIO DIMITRI ALEXOPULOS CASTILLO      VERDE    2.0
4          ARIEL ULISES VALLARINO APARICIO       C.D.   44.0
5              CEFERINO RODRIGUEZ ESPINOSA        PAN   42.0
5              CEFERINO RODRIGUEZ ESPINOSA    POPULAR    7.0
6                       CESAR VASQUEZ RICO     F.A.D.    4.0
7         DAVID VICTORIANO GUARDIA QUIJADA        PAN   40.0
8                   ERNESTO GIL VEGA REYES    POPULAR    7.0

In [ ]:
x=df['Candidato'].unique()
pd.DataFrame(x).sort_values(by=[0], ascending=True ).head(60)

                                        0
37                        HARMODIO GARCIA
0                    ALEXIS JIMENEZ OLIVA
36                       ALFREDO JONES M.
1             ALGIS TEOVALDO TORRES PEREZ
2   ALINA INES GONZALEZ CORDOBA DE CEDEÑO
39            ANA GISELLE R. DE VALLARINO
40                   ANDRES ALVAREZ RUEDA
3     ANTONIO DIMITRI ALEXOPULOS CASTILLO
4         ARIEL ULISES VALLARINO APARICIO
35                        BARTOLO HERRERA
41                BRIGIDO CAMAÑO MARTINEZ
5             CEFERINO RODRIGUEZ ESPINOSA
6                      CESAR VASQUEZ RICO
42                           DANIEL GOMEZ
7        DAVID VICTORIANO GUARDIA QUIJADA
43                   EDITH DE BETHANCOURT
8                  ERNESTO GIL VEGA REYES
9          GENESIS CHRISTINE ARJONA GOMEZ
10   GRETTA ELENA CARRILLO VEGA DE ORTEGA
44                       GUBERTO GRAJALES
26                        HARMODIO GARCIA
25                          HECTOR CEDEÑO
45                      HILARIO RODRIGUEZ
47                         IRVING GUARDIA
46                IRVING MANOLO CERVANTES
11               JOEL AMETH GIRON CAMARGO
28                           JULIO TAYLOR
30                  JURIKO ROXANA URRIOLA
32                           LEO GONZALEZ
33                 LORENA GONZÁLEZ ORTEGA
12          LUIS ALEXANDER BARRIA MOSCOSO
13             LUIS ANTONIO ALDEANO ORTIZ
31                            LUIS BARRIA
14                    LUIS GONZALEZ MARIN
48                   LUIS LUCHO RODRIGUEZ
15                        LUIS RAUL FIOTT
49                          MARIO GONGORA
50                    MARTHA DE GUTIERREZ
29                     MIGUEL MIKE VALERO
51                      MODESTO CERRUD D.
16                NEMESIO CASTRO GONZALEZ
24                          QUIBIAN PANAY
17                      RAUL PACHECO CRUZ
38               REINA LILIANA DE SANCHEZ
18          ROBERTO CARLOS RODRIGUEZ LOBO
19             ROBERTO JESUS LUCERO NUÑEZ
52                          ROSENDO FRIAS
53                         RUBEN QUINTERO
54             SILBESTRA M. FLORES SILVIA
20                   TITO RODRIGUEZ MENA
21                     VIDAL GARCIA UREÑA
34                      WIGBERTO QUINTERO
22        YAMILETH DEL CARMEN PAZ REINOSO
23       YASSIR ABOOBEKER PURCAIT SABORIO
27                      ZULPHY SANTAMARÍA

Significa que el partido elegido para los candidatos puede fallar con la formula elegida en EXCEL. La que funciona a cabalidad es con MELT

In [ ]:
dfn

,Distrito,Circuito,AÑO,Corregimiento,Centro,PARTIDO,Candidatol,MESA,ELECTORES,EMITIDOS,...,CHOCOLATE,PL,UP,VMP,TOTALES,% MESA POR ESCUELA,% DE PARTICIPACION,Candidato,variable,value
0,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,CHOCOLATE,ALEXIS JIMENEZ OLIVA,3606.0,498.0,256.0,...,4.0,0.0,0.0,0.0,4,0.007421,0.514056,ALEXIS JIMENEZ OLIVA,CHOCOLATE,4.0
1,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,ALIANZA,ALGIS TEOVALDO TORRES PEREZ,3606.0,498.0,256.0,...,0.0,0.0,0.0,0.0,8,0.014842,0.514056,ALGIS TEOVALDO TORRES PEREZ,ALIANZA,8.0
2,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,P.R.D.,ALINA INES GONZALEZ CORDOBA DE CEDEÑO,3606.0,498.0,256.0,...,0.0,0.0,0.0,0.0,58,0.107607,0.514056,ALINA INES GONZALEZ CORDOBA DE CEDEÑO,P.R.D.,58.0
3,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,VERDE,ANTONIO DIMITRI ALEXOPULOS CASTILLO,3606.0,498.0,256.0,...,0.0,0.0,0.0,0.0,2,0.003711,0.514056,ANTONIO DIMITRI ALEXOPULOS CASTILLO,VERDE,2.0
4,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,C.D.,ARIEL ULISES VALLARINO APARICIO,3606.0,498.0,256.0,...,0.0,0.0,0.0,0.0,44,0.081633,0.514056,ARIEL ULISES VALLARINO APARICIO,C.D.,44.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15822,PANAMÁ,44782.0,2009.0,LAS CUMBRES,ESC. LA CABIMA,UP,RUBEN QUINTERO,3857.0,501.0,343.0,...,0.0,0.0,7.0,0.0,7,0.010432,0.684631,RUBEN QUINTERO,UP,7.0
15823,PANAMÁ,44782.0,2009.0,LAS CUMBRES,ESC. LA CABIMA,VMP,SILBESTRA M. FLORES SILVIA,3857.0,501.0,343.0,...,0.0,0.0,0.0,1.0,1,0.00149,0.684631,SILBESTRA M. FLORES SILVIA,VMP,1.0
15824,PANAMÁ,44782.0,2009.0,LAS CUMBRES,ESC. LA CABIMA,C.D.,VIDAL GARCIA UREÑA,3857.0,501.0,343.0,...,0.0,0.0,0.0,0.0,79,0.117735,0.684631,VIDAL GARCIA UREÑA,C.D.,79.0
15825,PANAMÁ,44782.0,2009.0,LAS CUMBRES,ESC. LA CABIMA,C.D.,WIGBERTO QUINTERO,3857.0,501.0,343.0,...,0.0,0.0,0.0,0.0,94,0.140089,0.684631,WIGBERTO QUINTERO,C.D.,94.0
15826,PANAMÁ,44782.0,2009.0,LAS CUMBRES,ESC. LA CABIMA,P.R.D.,YASSIR ABOOBEKER PURCAIT SABORIO,3857.0,501.0,343.0,...,0.0,0.0,0.0,0.0,44,0.065574,0.684631,YASSIR ABOOBEKER PURCAIT SABORIO,P.R.D.,44.0

In [ ]:
#Verificaremos si la suma de values y totales es la misma
print(dfn['value'].sum()==df['TOTALES'].sum())

True

In [ ]:
def format_n(dfn):
  cols = dfn.columns.to_list()
  dfn=dfn.drop(columns=cols[13:26])
  dfn.drop(columns=['TOTALES','Candidatol','PARTIDO'],inplace=True)
  dfn=dfn.rename(columns={'variable':'Partido', 'value':'votos'})
  return dfn

In [ ]:
dfn = format_n(dfn)

Exportaremos la data depurada, con los partidos que son con sus respectivos votos

In [ ]:
#dfn.to_excel('/content/drive/MyDrive/ESTADISTICA DIPUTADO - REPRESENTANTE - debug.xlsx')

### Estudiando de Mesas

In [ ]:
dfn['MESA'].nunique()

649

In [ ]:
cols

['Distrito',
 'Circuito',
 'AÑO',
 'Corregimiento',
 'Centro',
 'PARTIDO',
 'Candidato',
 'MESA',
 'ELECTORES',
 'EMITIDOS',
 'VALIDOS',
 'BLANCOS',
 'NULOS',
 'P.R.D.',
 'POPULAR',
 'MOLIRENA',
 'PAN',
 'C.D.',
 'F.A.D.',
 'ALIANZA',
 'CELESTE',
 'VERDE',
 'CHOCOLATE',
 'PL',
 'UP',
 'VMP',
 'TOTALES',
 '% MESA POR ESCUELA',
 '% DE PARTICIPACION']

In [ ]:
cols2=dfn.columns.to_list()
cols2

['Distrito',
 'Circuito',
 'AÑO',
 'Corregimiento',
 'Centro',
 'MESA',
 'ELECTORES',
 'EMITIDOS',
 'VALIDOS',
 'BLANCOS',
 'NULOS',
 '% MESA POR ESCUELA',
 '% DE PARTICIPACION',
 'Candidato',
 'Partido',
 'votos']

In [ ]:
df_mesa=dfn[cols2[0:11]]
df_mesa['votos']=dfn['votos']
df_mesa.groupby(['AÑO','MESA'])[['ELECTORES']].mean()

df_mesa=df_mesa.groupby(df_mesa.columns.to_list()[0:-1])[['votos']].sum()
df_mesa.reset_index(inplace=True)
df_mesa

df_mesa.sort_values(by=['MESA'], inplace=True)
df_mesa.reset_index(inplace=True, drop=True)

Hay mesas duplicadas, trataremos de entender el ¿por qué?

In [ ]:
df_mesa[df_mesa['MESA'].duplicated()==True]

,Distrito,Circuito,AÑO,Corregimiento,Centro,MESA,ELECTORES,EMITIDOS,VALIDOS,BLANCOS,NULOS,votos
95,PANAMÁ,8-9,2019.0,LAS CUMBRES,ESC. BILINGÜE REPÚBLICA DE LA INDIA,3701.0,490.0,357.0,337.0,17.0,3.0,607.0
97,PANAMÁ,44782.0,2009.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3702.0,485.0,300.0,276.0,12.0,12.0,560.0
99,PANAMÁ,44782.0,2009.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3703.0,485.0,329.0,301.0,17.0,11.0,639.0
101,PANAMÁ,44782.0,2009.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3704.0,485.0,350.0,319.0,19.0,12.0,667.0
103,PANAMÁ,44782.0,2009.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3705.0,485.0,323.0,312.0,6.0,5.0,638.0
...,...,...,...,...,...,...,...,...,...,...,...,...
578,PANAMÁ,8-9,2019.0,ERNESTO CÓRDOBA CAMPOS,INST. POLITÉCNICO BILINGUE GOSEN,4182.0,514.0,399.0,373.0,9.0,17.0,653.0
580,PANAMÁ,8-9,2019.0,ERNESTO CÓRDOBA CAMPOS,INST. POLITÉCNICO BILINGUE GOSEN,4183.0,514.0,306.0,280.0,5.0,21.0,507.0
582,PANAMÁ,44782.0,2014.0,CHILIBRE,CE.FA.CE.I RAYITOS DE LUZ,4184.0,400.0,325.0,274.0,16.0,35.0,274.0
627,PANAMÁ,44782.0,2014.0,LAS CUMBRES,ESC. REP. DE LA INDIA,4228.0,421.0,308.0,274.0,10.0,24.0,56.0
673,PANAMÁ,44782.0,2014.0,ALCALDE DÍAZ,ESC. MELCHOR LASSO,4545.0,480.0,392.0,341.0,11.0,40.0,255.0

In [ ]:
df_mesa.loc[95:100]

,Distrito,Circuito,AÑO,Corregimiento,Centro,MESA,ELECTORES,EMITIDOS,VALIDOS,BLANCOS,NULOS,votos
95,PANAMÁ,8-9,2019.0,LAS CUMBRES,ESC. BILINGÜE REPÚBLICA DE LA INDIA,3701.0,490.0,357.0,337.0,17.0,3.0,607.0
96,PANAMÁ,8-9,2019.0,LAS CUMBRES,ESC. BILINGÜE REPÚBLICA DE LA INDIA,3702.0,490.0,377.0,328.0,10.0,39.0,660.0
97,PANAMÁ,44782.0,2009.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3702.0,485.0,300.0,276.0,12.0,12.0,560.0
98,PANAMÁ,8-9,2019.0,LAS CUMBRES,ESC. BILINGÜE REPÚBLICA DE LA INDIA,3703.0,488.0,360.0,335.0,13.0,12.0,618.0
99,PANAMÁ,44782.0,2009.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3703.0,485.0,329.0,301.0,17.0,11.0,639.0
100,PANAMÁ,8-9,2019.0,LAS CUMBRES,ESC. BILINGÜE REPÚBLICA DE LA INDIA,3704.0,488.0,323.0,293.0,5.0,25.0,595.0

In [ ]:
df_mesa['MESA'].max()

4666.0

Las mesas duplicadas eran por la diferencia de años, por lo que en realidad no es un dato duplicado. Por lo que podemos exportar nuestro dataframe sin inconvenientes

In [ ]:
#df_mesa.to_excel('/content/drive/MyDrive/Votaciones - Debug/mesa.xlsx')

### Ganadores: Cociente, Medio Cociente y Residuo

Los ganadores se definen de la siguiente forma:
1. Cociente: Cantidad de votos válidos entre la cantidad de curules (por partido)
2. Medio Cociente: Cociente entre 2. No pueden ganar los partidos que ya habían ganado por cociente
3. Residuo: Al partido del candidato que más votos ha tenido, contando todos los partidos afiliados

En el circuito 8-9 se tienen 3 curules a la fecha. En las votaciones de los 3 años se han mantenido de esa forma. Primero veremos los ganadores de cociente y medio cociente

In [ ]:
curules=3
df_curules=df_mesa.groupby(['AÑO'])[['EMITIDOS']].sum()

In [ ]:
df_curules

        EMITIDOS
AÑO
2009.0   66781.0
2014.0   83405.0
2019.0   89067.0

### Cociente y Medio Cociente

Establecemos los límites de cociente y medio cociente para su cálculo

In [ ]:
df_curules['cociente']=df_curules['EMITIDOS']/curules
df_curules['m_cociente']=df_curules['EMITIDOS']/curules/2

In [ ]:
df_curules

        EMITIDOS      cociente    m_cociente
AÑO
2009.0   66781.0  22260.333333  11130.166667
2014.0   83405.0  27801.666667  13900.833333
2019.0   89067.0  29689.000000  14844.500000

In [ ]:
dfn.groupby(['AÑO', 'Partido'])[['votos']].sum()

                    votos
AÑO    Partido
2009.0 C.D.       38880.0
       CELESTE     2725.0
       MOLIRENA    3540.0
       P.R.D.     39311.0
       PAN        31757.0
       POPULAR     2380.0
       UP          3380.0
       VERDE        997.0
       VMP         1042.0
2014.0 ALIANZA        1.0
       C.D.       21188.0
       F.A.D.       919.0
       MOLIRENA   12905.0
       P.R.D.     17103.0
       PAN        17798.0
       POPULAR     2530.0
2019.0 ALIANZA     6191.0
       C.D.       42655.0
       CELESTE     6981.0
       CHOCOLATE   3138.0
       F.A.D.      3369.0
       MOLIRENA   14196.0
       P.R.D.     41505.0
       PAN        26717.0
       POPULAR     3666.0
       VERDE       8419.0

In [ ]:
votos_tribunal = {'P.R.D.':	21791,
                'POPULAR':	1757,
                'MOLIRENA':	6808,
                'PAN':	12351,
                'C.D.':	21194,
                'F.A.D.'	:1435,
                'ALIANZA'	:3011,
                'CELESTE'	:7038,
                'VERDE'	:3763,
                'CHOCOLATE'	:3169}

agregando valores de TE de votos

In [ ]:
votos_partido=dfn[dfn['AÑO']==2019][['AÑO','Partido']]
#votos_partido=votos_partido[['AÑO','Partido']]
votos_partido['votos_partido_TE']=votos_partido['Partido'].apply(lambda x: votos_tribunal.get(x))
votos_partido['key_votos_p']=votos_partido['AÑO'].astype(str)+'-'+votos_partido['Partido']
votos_partido.set_index('key_votos_p', inplace=True)

In [ ]:
df_curules

        EMITIDOS      cociente    m_cociente
AÑO
2009.0   66781.0  22260.333333  11130.166667
2014.0   83405.0  27801.666667  13900.833333
2019.0   89067.0  29689.000000  14844.500000

In [ ]:
dfwin=dfn.groupby(['AÑO', 'Partido'])[['votos']].sum()
dfwin.join(df_curules, on=['AÑO'])

                    votos  EMITIDOS      cociente    m_cociente
AÑO    Partido
2009.0 C.D.       38880.0   66781.0  22260.333333  11130.166667
       CELESTE     2725.0   66781.0  22260.333333  11130.166667
       MOLIRENA    3540.0   66781.0  22260.333333  11130.166667
       P.R.D.     39311.0   66781.0  22260.333333  11130.166667
       PAN        31757.0   66781.0  22260.333333  11130.166667
       POPULAR     2380.0   66781.0  22260.333333  11130.166667
       UP          3380.0   66781.0  22260.333333  11130.166667
       VERDE        997.0   66781.0  22260.333333  11130.166667
       VMP         1042.0   66781.0  22260.333333  11130.166667
2014.0 ALIANZA        1.0   83405.0  27801.666667  13900.833333
       C.D.       21188.0   83405.0  27801.666667  13900.833333
       F.A.D.       919.0   83405.0  27801.666667  13900.833333
       MOLIRENA   12905.0   83405.0  27801.666667  13900.833333
       P.R.D.     17103.0   83405.0  27801.666667  13900.833333
       PAN        17798.0   83405.0  27801.666667  13900.833333
       POPULAR     2530.0   83405.0  27801.666667  13900.833333
2019.0 ALIANZA     6191.0   89067.0  29689.000000  14844.500000
       C.D.       42655.0   89067.0  29689.000000  14844.500000
       CELESTE     6981.0   89067.0  29689.000000  14844.500000
       CHOCOLATE   3138.0   89067.0  29689.000000  14844.500000
       F.A.D.      3369.0   89067.0  29689.000000  14844.500000
       MOLIRENA   14196.0   89067.0  29689.000000  14844.500000
       P.R.D.     41505.0   89067.0  29689.000000  14844.500000
       PAN        26717.0   89067.0  29689.000000  14844.500000
       POPULAR     3666.0   89067.0  29689.000000  14844.500000
       VERDE       8419.0   89067.0  29689.000000  14844.500000

In [ ]:
dfwin.reset_index(inplace=True)
#dfwin['key_votos_p']=dfwin['AÑO'].astype(str)+'-'+dfwin['Partido']
#dfwin=dfwin.join(votos_partido['votos_partido_TE'], on=['key_votos_p'])
#dfwin['votos_partido_TE'].fillna(0, inplace=True)

#dfwin['votos']=dfwin['votos']+dfwin['votos_partido_TE']

In [ ]:
a=dfwin.iloc[16:]
a['votos']=a['Partido'].apply(lambda x: votos_tribunal.get(x))

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
dfwin.drop(index=(range(16,26)), inplace=True)
dfwin=dfwin.append(a)

In [ ]:
dfwin=dfwin.join(df_curules, on=['AÑO'])

In [ ]:
dfwin['win_cociente']=dfwin['votos']-dfwin['cociente']
dfwin['win_cociente']=dfwin['win_cociente'].apply(lambda x:1 if x>0 else 0)

In [ ]:
dfwin.sort_values(by=['AÑO','votos'], ascending=False)

,AÑO,Partido,votos,EMITIDOS,cociente,m_cociente,win_cociente
22,2019.0,P.R.D.,21791.0,89067.0,29689.000000,14844.500000,0
17,2019.0,C.D.,21194.0,89067.0,29689.000000,14844.500000,0
23,2019.0,PAN,12351.0,89067.0,29689.000000,14844.500000,0
18,2019.0,CELESTE,7038.0,89067.0,29689.000000,14844.500000,0
21,2019.0,MOLIRENA,6808.0,89067.0,29689.000000,14844.500000,0
25,2019.0,VERDE,3763.0,89067.0,29689.000000,14844.500000,0
19,2019.0,CHOCOLATE,3169.0,89067.0,29689.000000,14844.500000,0
16,2019.0,ALIANZA,3011.0,89067.0,29689.000000,14844.500000,0
24,2019.0,POPULAR,1757.0,89067.0,29689.000000,14844.500000,0
20,2019.0,F.A.D.,1435.0,89067.0,29689.000000,14844.500000,0
10,2014.0,C.D.,21188.0,83405.0,27801.666667,13900.833333,0
14,2014.0,PAN,17798.0,83405.0,27801.666667,13900.833333,0
13,2014.0,P.R.D.,17103.0,83405.0,27801.666667,13900.833333,0
12,2014.0,MOLIRENA,12905.0,83405.0,27801.666667,13900.833333,0
15,2014.0,POPULAR,2530.0,83405.0,27801.666667,13900.833333,0
11,2014.0,F.A.D.,919.0,83405.0,27801.666667,13900.833333,0
9,2014.0,ALIANZA,1.0,83405.0,27801.666667,13900.833333,0
3,2009.0,P.R.D.,39311.0,66781.0,22260.333333,11130.166667,1
0,2009.0,C.D.,38880.0,66781.0,22260.333333,11130.166667,1
4,2009.0,PAN,31757.0,66781.0,22260.333333,11130.166667,1
2,2009.0,MOLIRENA,3540.0,66781.0,22260.333333,11130.166667,0
6,2009.0,UP,3380.0,66781.0,22260.333333,11130.166667,0
1,2009.0,CELESTE,2725.0,66781.0,22260.333333,11130.166667,0
5,2009.0,POPULAR,2380.0,66781.0,22260.333333,11130.166667,0
8,2009.0,VMP,1042.0,66781.0,22260.333333,11130.166667,0
7,2009.0,VERDE,997.0,66781.0,22260.333333,11130.166667,0

In [ ]:
dfwin['win_m_cociente']=dfwin['votos']-dfwin['m_cociente']
dfwin['win_m_cociente']=dfwin['win_m_cociente'].apply(lambda x:1 if x>0 else 0)

In [ ]:
dfwin['real_m_cociente']=dfwin['win_m_cociente']-dfwin['win_cociente']

Recordemos que los ganadores en medio cociente no pueden haber ganado en cociente, por lo que las curules ganadas como medio cociente serían real_m_cociente

Como solo son 3 curules, habría que obtener los 3 con más votos en cociente, si no se llenan, entonces los medio cociente y por último entraría la figura del Residuo.

In [ ]:
#dfwin=dfwin.sort_values(by=['AÑO','votos','win_cociente','real_m_cociente'], ascending=False)
dfwin=dfwin.sort_values(by=['AÑO','votos','win_cociente'], ascending=False)

In [ ]:
dfwin

,AÑO,Partido,votos,EMITIDOS,cociente,m_cociente,win_cociente,win_m_cociente,real_m_cociente
22,2019.0,P.R.D.,21791.0,89067.0,29689.000000,14844.500000,0,1,1
17,2019.0,C.D.,21194.0,89067.0,29689.000000,14844.500000,0,1,1
23,2019.0,PAN,12351.0,89067.0,29689.000000,14844.500000,0,0,0
18,2019.0,CELESTE,7038.0,89067.0,29689.000000,14844.500000,0,0,0
21,2019.0,MOLIRENA,6808.0,89067.0,29689.000000,14844.500000,0,0,0
25,2019.0,VERDE,3763.0,89067.0,29689.000000,14844.500000,0,0,0
19,2019.0,CHOCOLATE,3169.0,89067.0,29689.000000,14844.500000,0,0,0
16,2019.0,ALIANZA,3011.0,89067.0,29689.000000,14844.500000,0,0,0
24,2019.0,POPULAR,1757.0,89067.0,29689.000000,14844.500000,0,0,0
20,2019.0,F.A.D.,1435.0,89067.0,29689.000000,14844.500000,0,0,0
10,2014.0,C.D.,21188.0,83405.0,27801.666667,13900.833333,0,1,1
14,2014.0,PAN,17798.0,83405.0,27801.666667,13900.833333,0,1,1
13,2014.0,P.R.D.,17103.0,83405.0,27801.666667,13900.833333,0,1,1
12,2014.0,MOLIRENA,12905.0,83405.0,27801.666667,13900.833333,0,0,0
15,2014.0,POPULAR,2530.0,83405.0,27801.666667,13900.833333,0,0,0
11,2014.0,F.A.D.,919.0,83405.0,27801.666667,13900.833333,0,0,0
9,2014.0,ALIANZA,1.0,83405.0,27801.666667,13900.833333,0,0,0
3,2009.0,P.R.D.,39311.0,66781.0,22260.333333,11130.166667,1,1,0
0,2009.0,C.D.,38880.0,66781.0,22260.333333,11130.166667,1,1,0
4,2009.0,PAN,31757.0,66781.0,22260.333333,11130.166667,1,1,0
2,2009.0,MOLIRENA,3540.0,66781.0,22260.333333,11130.166667,0,0,0
6,2009.0,UP,3380.0,66781.0,22260.333333,11130.166667,0,0,0
1,2009.0,CELESTE,2725.0,66781.0,22260.333333,11130.166667,0,0,0
5,2009.0,POPULAR,2380.0,66781.0,22260.333333,11130.166667,0,0,0
8,2009.0,VMP,1042.0,66781.0,22260.333333,11130.166667,0,0,0
7,2009.0,VERDE,997.0,66781.0,22260.333333,11130.166667,0,0,0

In [ ]:
dfwin['ganadores']=dfwin['win_cociente']+dfwin['real_m_cociente']

In [ ]:
dfwin=dfwin.sort_values(by=['AÑO','votos','ganadores'], ascending=False)


Nota: Usaremos estas líneas para hacer suma acumulada y reset cuando hay 0

In [ ]:
a = dfwin['ganadores'] != 0
df1 = a.cumsum()-a.cumsum().where(~a).ffill().fillna(0).astype(int)

In [ ]:
df1=pd.DataFrame(df1)
df1['ganadores']=df1['ganadores'].apply(lambda x: x if x<=curules else 0 )

In [ ]:
dfwin=dfwin.join(df1, rsuffix='_final')

Uniendo ahora los ganadores con el DFn

In [ ]:
dfwin.reset_index(inplace=True)
dfwin['key-cocientes'] = dfwin['AÑO'].astype(str) + '-' + dfwin['Partido']
dfwin2 = dfwin[['ganadores','ganadores_final','key-cocientes']]
dfwin2.set_index('key-cocientes',inplace=True)
dfn['key-cocientes']=dfn['AÑO'].astype(str) + '-' + dfn['Partido']
dfn=dfn.join(dfwin2, on=['key-cocientes'])

In [ ]:
df_dips_cocientes=dfn[dfn['ganadores_final']!=0]

In [ ]:
def dip_win(df): #Función para hacer el ranking por año
  df=df.groupby(['AÑO','Partido','Candidato'])[['votos']].sum()
  df.reset_index(inplace=True)
  years=df['AÑO'].unique()
  partido = df['Partido'].unique()
  df1= df.head(0)
  for i in years:
    for x in partido:
      df['diputado']=df[(df['AÑO'] == i)&(df['Partido'] == x)]['votos'].rank(ascending=False)
      df1=df1.append(df)

  df1.dropna(inplace=True)
  df1=df1[df1['diputado']==1]
  return df1

In [ ]:
df_dips_cocientes=dip_win(df_dips_cocientes)

In [ ]:
df_dips_cocientes['key-diputado']=df_dips_cocientes['AÑO'].astype(str)+'-'+df_dips_cocientes['Partido']+'-'+df_dips_cocientes['Candidato']
df_dips_cocientes.set_index('key-diputado', inplace=True)

In [ ]:
dfn['key-diputado']=dfn['AÑO'].astype(str)+'-'+dfn['Partido']+'-'+dfn['Candidato']

In [ ]:
dfn=dfn.join(df_dips_cocientes['diputado'], on=['key-diputado'])
dfn['diputado'].fillna(0, inplace=True)

In [ ]:
dfn

,Distrito,Circuito,AÑO,Corregimiento,Centro,MESA,ELECTORES,EMITIDOS,VALIDOS,BLANCOS,...,% MESA POR ESCUELA,% DE PARTICIPACION,Candidato,Partido,votos,key-cocientes,ganadores,ganadores_final,key-diputado,diputado
0,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3606.0,498.0,256.0,235.0,16.0,...,0.007421,0.514056,ALEXIS JIMENEZ OLIVA,CHOCOLATE,4.0,2019.0-CHOCOLATE,0.0,0.0,2019.0-CHOCOLATE-ALEXIS JIMENEZ OLIVA,0.0
1,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3606.0,498.0,256.0,235.0,16.0,...,0.014842,0.514056,ALGIS TEOVALDO TORRES PEREZ,ALIANZA,8.0,2019.0-ALIANZA,0.0,0.0,2019.0-ALIANZA-ALGIS TEOVALDO TORRES PEREZ,0.0
2,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3606.0,498.0,256.0,235.0,16.0,...,0.107607,0.514056,ALINA INES GONZALEZ CORDOBA DE CEDEÑO,P.R.D.,58.0,2019.0-P.R.D.,1.0,1.0,2019.0-P.R.D.-ALINA INES GONZALEZ CORDOBA DE C...,1.0
3,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3606.0,498.0,256.0,235.0,16.0,...,0.003711,0.514056,ANTONIO DIMITRI ALEXOPULOS CASTILLO,VERDE,2.0,2019.0-VERDE,0.0,0.0,2019.0-VERDE-ANTONIO DIMITRI ALEXOPULOS CASTILLO,0.0
4,PANAMÁ,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3606.0,498.0,256.0,235.0,16.0,...,0.081633,0.514056,ARIEL ULISES VALLARINO APARICIO,C.D.,44.0,2019.0-C.D.,1.0,2.0,2019.0-C.D.-ARIEL ULISES VALLARINO APARICIO,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15822,PANAMÁ,44782.0,2009.0,LAS CUMBRES,ESC. LA CABIMA,3857.0,501.0,343.0,320.0,19.0,...,0.010432,0.684631,RUBEN QUINTERO,UP,7.0,2009.0-UP,0.0,0.0,2009.0-UP-RUBEN QUINTERO,0.0
15823,PANAMÁ,44782.0,2009.0,LAS CUMBRES,ESC. LA CABIMA,3857.0,501.0,343.0,320.0,19.0,...,0.00149,0.684631,SILBESTRA M. FLORES SILVIA,VMP,1.0,2009.0-VMP,0.0,0.0,2009.0-VMP-SILBESTRA M. FLORES SILVIA,0.0
15824,PANAMÁ,44782.0,2009.0,LAS CUMBRES,ESC. LA CABIMA,3857.0,501.0,343.0,320.0,19.0,...,0.117735,0.684631,VIDAL GARCIA UREÑA,C.D.,79.0,2009.0-C.D.,1.0,2.0,2009.0-C.D.-VIDAL GARCIA UREÑA,1.0
15825,PANAMÁ,44782.0,2009.0,LAS CUMBRES,ESC. LA CABIMA,3857.0,501.0,343.0,320.0,19.0,...,0.140089,0.684631,WIGBERTO QUINTERO,C.D.,94.0,2009.0-C.D.,1.0,2.0,2009.0-C.D.-WIGBERTO QUINTERO,0.0
15826,PANAMÁ,44782.0,2009.0,LAS CUMBRES,ESC. LA CABIMA,3857.0,501.0,343.0,320.0,19.0,...,0.065574,0.684631,YASSIR ABOOBEKER PURCAIT SABORIO,P.R.D.,44.0,2009.0-P.R.D.,1.0,1.0,2009.0-P.R.D.-YASSIR ABOOBEKER PURCAIT SABORIO,1.0

### RESIDUO

Calcularemos el ranking individual de candidato. En este caso particular por la cantidad de curules no entraron por residuo, sin embargo con las cantidades suficientes podríamos ver cuáles candidatos entrarían por residuo

Para ello, primero removeremos los diputados ganadores por cociente y medio cociente

In [ ]:
df_dips_cocientes.reset_index(drop=True, inplace=True)
df_dips_cocientes['dip_res'] = df_dips_cocientes['AÑO'].astype(str)+'-'+df_dips_cocientes['Candidato']
df_dips_cocientes.set_index('dip_res',inplace=True)

In [ ]:
df_dips_cocientes

,AÑO,Partido,Candidato,votos,diputado
dip_res,,,,,
2009.0-VIDAL GARCIA UREÑA,2009.0,C.D.,VIDAL GARCIA UREÑA,13581.0,1.0
2009.0-YASSIR ABOOBEKER PURCAIT SABORIO,2009.0,P.R.D.,YASSIR ABOOBEKER PURCAIT SABORIO,14899.0,1.0
2009.0-TITO RODRIGUEZ MENA,2009.0,PAN,TITO RODRIGUEZ MENA,11954.0,1.0
2014.0-VIDAL GARCIA UREÑA,2014.0,C.D.,VIDAL GARCIA UREÑA,11760.0,1.0
2014.0-QUIBIAN PANAY,2014.0,P.R.D.,QUIBIAN PANAY,12082.0,1.0
2014.0-LUIS BARRIA,2014.0,PAN,LUIS BARRIA,13774.0,1.0
2019.0-GENESIS CHRISTINE ARJONA GOMEZ,2019.0,C.D.,GENESIS CHRISTINE ARJONA GOMEZ,14902.0,1.0
2019.0-ALINA INES GONZALEZ CORDOBA DE CEDEÑO,2019.0,P.R.D.,ALINA INES GONZALEZ CORDOBA DE CEDEÑO,17424.0,1.0

In [ ]:
df_residuo=dfn.groupby(['AÑO','Candidato'])[['votos']].sum()

In [ ]:
df_residuo.reset_index(inplace=True)
df_residuo['dip_res']=df_residuo['AÑO'].astype(str)+'-'+df_residuo['Candidato']

In [ ]:
df_residuo=df_residuo.join(df_dips_cocientes['diputado'], on=['dip_res'])
df_residuo = df_residuo[df_residuo['diputado']!=1]
df_residuo.drop(columns=['diputado'],inplace=True)

In [ ]:
def ranking(df): #Función para hacer el ranking por año
  
  years=df['AÑO'].unique()
  df1= df.head(0)
  for i in years:
    df['top_res']=df[df['AÑO'] == i]['votos'].rank(ascending=False)
    df1=df1.append(df)

  df1.dropna(inplace=True)
  return df1

In [ ]:
df_residuo=ranking(df_residuo)

In [ ]:
df_residuo.sort_values(by=['AÑO','top_res'], ascending=True)

,AÑO,Candidato,votos,dip_res,top_res
22,2009.0,WIGBERTO QUINTERO,12974.0,2009.0-WIGBERTO QUINTERO,1.0
7,2009.0,HECTOR CEDEÑO,12939.0,2009.0-HECTOR CEDEÑO,2.0
0,2009.0,ALGIS TEOVALDO TORRES PEREZ,12325.0,2009.0-ALGIS TEOVALDO TORRES PEREZ,3.0
11,2009.0,LUIS BARRIA,11764.0,2009.0-LUIS BARRIA,4.0
12,2009.0,LUIS LUCHO RODRIGUEZ,11473.0,2009.0-LUIS LUCHO RODRIGUEZ,5.0
8,2009.0,HILARIO RODRIGUEZ,8039.0,2009.0-HILARIO RODRIGUEZ,6.0
1,2009.0,ANA GISELLE R. DE VALLARINO,1923.0,2009.0-ANA GISELLE R. DE VALLARINO,7.0
15,2009.0,MODESTO CERRUD D.,1617.0,2009.0-MODESTO CERRUD D.,8.0
4,2009.0,DANIEL GOMEZ,1474.0,2009.0-DANIEL GOMEZ,9.0
6,2009.0,GUBERTO GRAJALES,997.0,2009.0-GUBERTO GRAJALES,10.0
18,2009.0,RUBEN QUINTERO,974.0,2009.0-RUBEN QUINTERO,11.0
2,2009.0,ANDRES ALVAREZ RUEDA,939.0,2009.0-ANDRES ALVAREZ RUEDA,12.0
13,2009.0,MARIO GONGORA,932.0,2009.0-MARIO GONGORA,13.0
16,2009.0,REINA LILIANA DE SANCHEZ,907.0,2009.0-REINA LILIANA DE SANCHEZ,14.0
14,2009.0,MARTHA DE GUTIERREZ,879.0,2009.0-MARTHA DE GUTIERREZ,15.0
5,2009.0,EDITH DE BETHANCOURT,860.0,2009.0-EDITH DE BETHANCOURT,16.0
9,2009.0,IRVING GUARDIA,776.0,2009.0-IRVING GUARDIA,17.0
17,2009.0,ROSENDO FRIAS,744.0,2009.0-ROSENDO FRIAS,18.0
10,2009.0,IRVING MANOLO CERVANTES,363.0,2009.0-IRVING MANOLO CERVANTES,19.0
19,2009.0,SILBESTRA M. FLORES SILVIA,347.0,2009.0-SILBESTRA M. FLORES SILVIA,20.0
3,2009.0,BRIGIDO CAMAÑO MARTINEZ,332.0,2009.0-BRIGIDO CAMAÑO MARTINEZ,21.0
39,2014.0,TITO RODRIGUEZ MENA,11814.0,2014.0-TITO RODRIGUEZ MENA,1.0
26,2014.0,ALGIS TEOVALDO TORRES PEREZ,6957.0,2014.0-ALGIS TEOVALDO TORRES PEREZ,2.0
29,2014.0,HECTOR CEDEÑO,4422.0,2014.0-HECTOR CEDEÑO,3.0
32,2014.0,LEO GONZALEZ,3357.0,2014.0-LEO GONZALEZ,4.0
41,2014.0,WIGBERTO QUINTERO,2484.0,2014.0-WIGBERTO QUINTERO,5.0
42,2014.0,ZULPHY SANTAMARÍA,1731.0,2014.0-ZULPHY SANTAMARÍA,6.0
31,2014.0,JURIKO ROXANA URRIOLA,765.0,2014.0-JURIKO ROXANA URRIOLA,7.0
37,2014.0,MIGUEL MIKE VALERO,746.0,2014.0-MIGUEL MIKE VALERO,8.0
33,2014.0,LORENA GONZÁLEZ ORTEGA,679.0,2014.0-LORENA GONZÁLEZ ORTEGA,9.0
35,2014.0,LUIS GONZALEZ MARIN,565.0,2014.0-LUIS GONZALEZ MARIN,10.0
28,2014.0,HARMODIO GARCIA,366.0,2014.0-HARMODIO GARCIA,11.0
30,2014.0,JULIO TAYLOR,329.0,2014.0-JULIO TAYLOR,12.0
27,2014.0,BARTOLO HERRERA,255.0,2014.0-BARTOLO HERRERA,13.0
36,2014.0,LUIS RAUL FIOTT,143.0,2014.0-LUIS RAUL FIOTT,14.0
25,2014.0,ALFREDO JONES M.,79.0,2014.0-ALFREDO JONES M.,15.0
24,2014.0,HARMODIO GARCIA,1.0,2014.0- HARMODIO GARCIA,16.0
63,2019.0,TITO RODRIGUEZ MENA,16026.0,2019.0-TITO RODRIGUEZ MENA,1.0
47,2019.0,ARIEL ULISES VALLARINO APARICIO,14410.0,2019.0-ARIEL ULISES VALLARINO APARICIO,2.0
66,2019.0,YASSIR ABOOBEKER PURCAIT SABORIO,13840.0,2019.0-YASSIR ABOOBEKER PURCAIT SABORIO,3.0
64,2019.0,VIDAL GARCIA UREÑA,13343.0,2019.0-VIDAL GARCIA UREÑA,4.0
55,2019.0,LUIS ALEXANDER BARRIA MOSCOSO,11759.0,2019.0-LUIS ALEXANDER BARRIA MOSCOSO,5.0
48,2019.0,CEFERINO RODRIGUEZ ESPINOSA,8640.0,2019.0-CEFERINO RODRIGUEZ ESPINOSA,6.0
50,2019.0,DAVID VICTORIANO GUARDIA QUIJADA,7579.0,2019.0-DAVID VICTORIANO GUARDIA QUIJADA,7.0
56,2019.0,LUIS ANTONIO ALDEANO ORTIZ,6981.0,2019.0-LUIS ANTONIO ALDEANO ORTIZ,8.0
53,2019.0,GRETTA ELENA CARRILLO VEGA DE ORTEGA,4208.0,2019.0-GRETTA ELENA CARRILLO VEGA DE ORTEGA,9.0
59,2019.0,NEMESIO CASTRO GONZALEZ,4203.0,2019.0-NEMESIO CASTRO GONZALEZ,10.0
43,2019.0,ALEXIS JIMENEZ OLIVA,3138.0,2019.0-ALEXIS JIMENEZ OLIVA,11.0
46,2019.0,ANTONIO DIMITRI ALEXOPULOS CASTILLO,2936.0,2019.0-ANTONIO DIMITRI ALEXOPULOS CASTILLO,12.0
44,2019.0,ALGIS TEOVALDO TORRES PEREZ,2847.0,2019.0-ALGIS TEOVALDO TORRES PEREZ,13.0
54,2019.0,JOEL AMETH GIRON CAMARGO,2753.0,2019.0-JOEL AMETH GIRON CAMARGO,14.0
61,2019.0,ROBERTO CARLOS RODRIGUEZ LOBO,2730.0,2019.0-ROBERTO CARLOS RODRIGUEZ LOBO,15.0
65,2019.0,YAMILETH DEL CARMEN PAZ REINOSO,1716.0,2019.0-YAMILETH DEL CARMEN PAZ REINOSO,16.0
60,2019.0,RAUL PACHECO CRUZ,1628.0,2019.0-RAUL PACHECO CRUZ,17.0
51,2019.0,ERNESTO GIL VEGA REYES,1392.0,2019.0-ERNESTO GIL VEGA REYES,18.0
57,2019.0,LUIS GONZALEZ MARIN,1156.0,2019.0-LUIS GONZALEZ MARIN,19.0
62,2019.0,ROBERTO JESUS LUCERO NUÑEZ,1150.0,2019.0-ROBERTO JESUS LUCERO NUÑEZ,20.0
49,2019.0,CESAR VASQUEZ RICO,1063.0,2019.0-CESAR VASQUEZ RICO,21.0
58,2019.0,LUIS RAUL FIOTT,1013.0,2019.0-LUIS RAUL FIOTT,22.0

### Uniendo DFn, los ganadores y los ranking de residuo

In [ ]:
dfn['k-residuo']=dfn['AÑO'].astype(str)+'-'+dfn['Candidato']
df_residuo['k-residuo']= df_residuo['AÑO'].astype(str)+'-'+df_residuo['Candidato']
df_residuo.set_index('k-residuo',inplace=True)

In [ ]:
df_residuo.drop(columns=['Candidato','votos', 'AÑO'], inplace=True)

In [ ]:
df_residuo

,dip_res,top_res
k-residuo,,
2009.0-ALGIS TEOVALDO TORRES PEREZ,2009.0-ALGIS TEOVALDO TORRES PEREZ,3.0
2009.0-ANA GISELLE R. DE VALLARINO,2009.0-ANA GISELLE R. DE VALLARINO,7.0
2009.0-ANDRES ALVAREZ RUEDA,2009.0-ANDRES ALVAREZ RUEDA,12.0
2009.0-BRIGIDO CAMAÑO MARTINEZ,2009.0-BRIGIDO CAMAÑO MARTINEZ,21.0
2009.0-DANIEL GOMEZ,2009.0-DANIEL GOMEZ,9.0
2009.0-EDITH DE BETHANCOURT,2009.0-EDITH DE BETHANCOURT,16.0
2009.0-GUBERTO GRAJALES,2009.0-GUBERTO GRAJALES,10.0
2009.0-HECTOR CEDEÑO,2009.0-HECTOR CEDEÑO,2.0
2009.0-HILARIO RODRIGUEZ,2009.0-HILARIO RODRIGUEZ,6.0
2009.0-IRVING GUARDIA,2009.0-IRVING GUARDIA,17.0
2009.0-IRVING MANOLO CERVANTES,2009.0-IRVING MANOLO CERVANTES,19.0
2009.0-LUIS BARRIA,2009.0-LUIS BARRIA,4.0
2009.0-LUIS LUCHO RODRIGUEZ,2009.0-LUIS LUCHO RODRIGUEZ,5.0
2009.0-MARIO GONGORA,2009.0-MARIO GONGORA,13.0
2009.0-MARTHA DE GUTIERREZ,2009.0-MARTHA DE GUTIERREZ,15.0
2009.0-MODESTO CERRUD D.,2009.0-MODESTO CERRUD D.,8.0
2009.0-REINA LILIANA DE SANCHEZ,2009.0-REINA LILIANA DE SANCHEZ,14.0
2009.0-ROSENDO FRIAS,2009.0-ROSENDO FRIAS,18.0
2009.0-RUBEN QUINTERO,2009.0-RUBEN QUINTERO,11.0
2009.0-SILBESTRA M. FLORES SILVIA,2009.0-SILBESTRA M. FLORES SILVIA,20.0
2009.0-WIGBERTO QUINTERO,2009.0-WIGBERTO QUINTERO,1.0
2014.0- HARMODIO GARCIA,2014.0- HARMODIO GARCIA,16.0
2014.0-ALFREDO JONES M.,2014.0-ALFREDO JONES M.,15.0
2014.0-ALGIS TEOVALDO TORRES PEREZ,2014.0-ALGIS TEOVALDO TORRES PEREZ,2.0
2014.0-BARTOLO HERRERA,2014.0-BARTOLO HERRERA,13.0
2014.0-HARMODIO GARCIA,2014.0-HARMODIO GARCIA,11.0
2014.0-HECTOR CEDEÑO,2014.0-HECTOR CEDEÑO,3.0
2014.0-JULIO TAYLOR,2014.0-JULIO TAYLOR,12.0
2014.0-JURIKO ROXANA URRIOLA,2014.0-JURIKO ROXANA URRIOLA,7.0
2014.0-LEO GONZALEZ,2014.0-LEO GONZALEZ,4.0
2014.0-LORENA GONZÁLEZ ORTEGA,2014.0-LORENA GONZÁLEZ ORTEGA,9.0
2014.0-LUIS GONZALEZ MARIN,2014.0-LUIS GONZALEZ MARIN,10.0
2014.0-LUIS RAUL FIOTT,2014.0-LUIS RAUL FIOTT,14.0
2014.0-MIGUEL MIKE VALERO,2014.0-MIGUEL MIKE VALERO,8.0
2014.0-TITO RODRIGUEZ MENA,2014.0-TITO RODRIGUEZ MENA,1.0
2014.0-WIGBERTO QUINTERO,2014.0-WIGBERTO QUINTERO,5.0
2014.0-ZULPHY SANTAMARÍA,2014.0-ZULPHY SANTAMARÍA,6.0
2019.0-ALEXIS JIMENEZ OLIVA,2019.0-ALEXIS JIMENEZ OLIVA,11.0
2019.0-ALGIS TEOVALDO TORRES PEREZ,2019.0-ALGIS TEOVALDO TORRES PEREZ,13.0
2019.0-ANTONIO DIMITRI ALEXOPULOS CASTILLO,2019.0-ANTONIO DIMITRI ALEXOPULOS CASTILLO,12.0
2019.0-ARIEL ULISES VALLARINO APARICIO,2019.0-ARIEL ULISES VALLARINO APARICIO,2.0
2019.0-CEFERINO RODRIGUEZ ESPINOSA,2019.0-CEFERINO RODRIGUEZ ESPINOSA,6.0
2019.0-CESAR VASQUEZ RICO,2019.0-CESAR VASQUEZ RICO,21.0
2019.0-DAVID VICTORIANO GUARDIA QUIJADA,2019.0-DAVID VICTORIANO GUARDIA QUIJADA,7.0
2019.0-ERNESTO GIL VEGA REYES,2019.0-ERNESTO GIL VEGA REYES,18.0
2019.0-GRETTA ELENA CARRILLO VEGA DE ORTEGA,2019.0-GRETTA ELENA CARRILLO VEGA DE ORTEGA,9.0
2019.0-JOEL AMETH GIRON CAMARGO,2019.0-JOEL AMETH GIRON CAMARGO,14.0
2019.0-LUIS ALEXANDER BARRIA MOSCOSO,2019.0-LUIS ALEXANDER BARRIA MOSCOSO,5.0
2019.0-LUIS ANTONIO ALDEANO ORTIZ,2019.0-LUIS ANTONIO ALDEANO ORTIZ,8.0
2019.0-LUIS GONZALEZ MARIN,2019.0-LUIS GONZALEZ MARIN,19.0
2019.0-LUIS RAUL FIOTT,2019.0-LUIS RAUL FIOTT,22.0
2019.0-NEMESIO CASTRO GONZALEZ,2019.0-NEMESIO CASTRO GONZALEZ,10.0
2019.0-RAUL PACHECO CRUZ,2019.0-RAUL PACHECO CRUZ,17.0
2019.0-ROBERTO CARLOS RODRIGUEZ LOBO,2019.0-ROBERTO CARLOS RODRIGUEZ LOBO,15.0
2019.0-ROBERTO JESUS LUCERO NUÑEZ,2019.0-ROBERTO JESUS LUCERO NUÑEZ,20.0
2019.0-TITO RODRIGUEZ MENA,2019.0-TITO RODRIGUEZ MENA,1.0
2019.0-VIDAL GARCIA UREÑA,2019.0-VIDAL GARCIA UREÑA,4.0
2019.0-YAMILETH DEL CARMEN PAZ REINOSO,2019.0-YAMILETH DEL CARMEN PAZ REINOSO,16.0
2019.0-YASSIR ABOOBEKER PURCAIT SABORIO,2019.0-YASSIR ABOOBEKER PURCAIT SABORIO,3.0

In [ ]:
dfn=dfn.join(df_residuo, on=['k-residuo'])

In [ ]:
len(dfn)

16389

In [ ]:
dfn.fillna(0, inplace=True)

In [ ]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

wb=gc.open_by_key('1VPZ9Nha_BoDTPhX1-heXl0tkAy1kOU3tv8nOb3jWlFQ')
ws=wb.worksheet('Sheet1')

In [ ]:
wb=gc.open_by_key('1VPZ9Nha_BoDTPhX1-heXl0tkAy1kOU3tv8nOb3jWlFQ')
ws=wb.worksheet('Sheet1')

#TO IMPORT THE WORKSHEET AS A DATAFRAME
#test=pd.DataFrame(ws.get_all_values())
#test=test.set_axis(test.iloc[0], axis=1).drop(0)
#test

In [ ]:
#ws.update([dfn.columns.tolist()] + dfn.values.tolist())

In [ ]:
#dfn.to_excel('/content/drive/MyDrive/Votaciones - Debug/ganadores.xlsx')

## **Rep Corregimiento**

In [ ]:
dfr=pd.read_excel('/content/drive/MyDrive/ESTADISTICA DIPUTADO - REPRESENTANTE.xlsx', sheet_name='REPRESENTANTES 09-19')

## Depurando y Ganadores de Rep de Corregimiento

In [ ]:
dfr['Candidato']= dfr['Candidato'].apply(lambda x: 'ZAIDY QUINTERO' if x=='Zaidy Del Rosario Quintero Arauz De Portugal' else
                      ('VIDAL GARCÍA' if x=='VIDAL GARCIA UREÑA' else
                       ('RICARDO ALBERTO PRECILLA' if x== 'Ricardo Alberto Precilla Carrion' else x)))

In [ ]:
dfr['CANDIDATO'] = dfr['Candidato'].apply(lambda x: str.upper(x))

In [ ]:
colsr=dfr.columns.to_list() 
#colsr

In [ ]:
#dfr.groupby(['AÑO','Corregimiento','CANDIDATO'])[['TOTALES']].sum().sort_values(by=['AÑO','Corregimiento','TOTALES'],ascending=False).head(50)

In [ ]:
dfr.fillna(0,inplace=True)
df1r=dfr[colsr[13:26]]

df1r['Candidato']=dfr['Candidato']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [ ]:
dfr

,Distrito,Circuito,AÑO,Corregimiento,Centro,PARTIDO,Candidato,MESA,ELECTORES,EMITIDOS,...,ALIANZA,CELESTE,VERDE,CHOCOLATE,PL,UP,VMP,TOTALES,% MESA POR ESCUELA,CANDIDATO
0,PANAMÁ,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CE MONSEÑOR FRANCISCO BECKMAN,P.R.D.,PABLO WONG PINEDA,4598.0,492.0,264.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,58,0.256637,PABLO WONG PINEDA
1,PANAMÁ,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CE MONSEÑOR FRANCISCO BECKMAN,POPULAR,ISMAEL ATENCIO,4598.0,492.0,264.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15,0.066372,ISMAEL ATENCIO
2,PANAMÁ,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CE MONSEÑOR FRANCISCO BECKMAN,MOLIRENA,FRANCISCO EL MAESTRO MAURE,4598.0,492.0,264.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14,0.061947,FRANCISCO EL MAESTRO MAURE
3,PANAMÁ,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CE MONSEÑOR FRANCISCO BECKMAN,P.A.N.,ISMAEL ATENCIO,4598.0,492.0,264.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67,0.296460,ISMAEL ATENCIO
4,PANAMÁ,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CE MONSEÑOR FRANCISCO BECKMAN,C.D.,RUBÉN MEDINA,4598.0,492.0,264.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,72,0.318584,RUBÉN MEDINA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5755,PANAMÁ,8-9,2019.0,CAIMITILLO,ESC. PARARÁ PURU,C.D.,Jose Luis Garcia Palacio,4316.0,89.0,57.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12,0.240000,JOSE LUIS GARCIA PALACIO
5756,PANAMÁ,8-9,2019.0,CAIMITILLO,ESC. PARARÁ PURU,VERDE,Luis Carlos Trejos Ariza,4316.0,89.0,57.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1,0.020000,LUIS CARLOS TREJOS ARIZA
5757,PANAMÁ,8-9,2019.0,CAIMITILLO,ESC. PARARÁ PURU,MOLIRENA,Rodolfo Precilla Carrion,4316.0,89.0,57.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6,0.120000,RODOLFO PRECILLA CARRION
5758,PANAMÁ,8-9,2019.0,CAIMITILLO,ESC. PARARÁ PURU,POPULAR,Sonia Edith Cuevas De Rubio,4316.0,89.0,57.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2,0.040000,SONIA EDITH CUEVAS DE RUBIO
5759,PANAMÁ,8-9,2019.0,CAIMITILLO,ESC. PARARÁ PURU,ALIANZA,Tomasito Lopez Rivas,4316.0,89.0,57.0,...,3.0,0.0,0.0,0.0,0.0,0.0,0.0,3,0.060000,TOMASITO LOPEZ RIVAS

In [ ]:
colsr[13:26]

['P.R.D.',
 'POPULAR',
 'MOLIRENA',
 'PAN',
 'C.D.',
 'F.A.D.',
 'ALIANZA',
 'CELESTE',
 'VERDE',
 'CHOCOLATE',
 'PL',
 'UP',
 'VMP']

In [ ]:
dfr_partido=dfr.groupby(['AÑO','Corregimiento','Centro','MESA'])[colsr[13:26]].max()
dfr_partido.reset_index(inplace=True)

In [ ]:
dfr_partido=dfr_partido.melt(id_vars=['AÑO','Corregimiento','Centro','MESA'], var_name='Partido', value_name='Cantidad')
dfr_partido.to_csv('/content/drive/MyDrive/Votaciones - Debug/dfr_partido.csv',index_label='index')

In [ ]:
def partido(df1):
  df1['key']=df1.index
  df1=df1.melt(id_vars=['Candidato','key'])
  df1=df1[df1['value']>0]
  #df1.set_index('key', inplace=True)
  df1=df1.sort_index(ascending=True)
  return df1

In [ ]:
df1r=partido(df1r)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
#df1r.reset_index(inplace=True, drop=True)

In [ ]:
df1r.sort_values(by=['key'],inplace=True)

In [ ]:
df1r.set_index('key',inplace=True)

In [ ]:
dfr=dfr.join(df1r, lsuffix='l')

In [ ]:
dfr.isnull().sum()

Distrito                0
Circuito                0
AÑO                     0
Corregimiento           0
Centro                  0
PARTIDO                 0
Candidatol              0
MESA                    0
ELECTORES               0
EMITIDOS                0
VALIDOS                 0
BLANCOS                 0
NULOS                   0
P.R.D.                  0
POPULAR                 0
MOLIRENA                0
PAN                     0
C.D.                    0
F.A.D.                  0
ALIANZA                 0
CELESTE                 0
VERDE                   0
CHOCOLATE               0
PL                      0
UP                      0
VMP                     0
TOTALES                 0
% MESA POR ESCUELA      0
CANDIDATO               0
Candidato             109
variable              109
value                 109
dtype: int64

In [ ]:
dfr.dropna(inplace=True)

In [ ]:
dfr.reset_index(inplace=True, drop=True)

In [ ]:
def format_n(dfn):
  cols = dfn.columns.to_list()
  dfn=dfn.drop(columns=cols[13:26])
  dfn.drop(columns=['Candidatol','PARTIDO'],inplace=True)
  dfn=dfn.rename(columns={'variable':'Partido', 'value':'votos'})
  return dfn

In [ ]:
dfr = format_n(dfr)
dfr

,Distrito,Circuito,AÑO,Corregimiento,Centro,MESA,ELECTORES,EMITIDOS,VALIDOS,BLANCOS,NULOS,TOTALES,% MESA POR ESCUELA,CANDIDATO,Candidato,Partido,votos
0,PANAMÁ,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CE MONSEÑOR FRANCISCO BECKMAN,4598.0,492.0,264.0,226.0,27.0,11.0,58,0.256637,PABLO WONG PINEDA,PABLO WONG PINEDA,P.R.D.,58.0
1,PANAMÁ,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CE MONSEÑOR FRANCISCO BECKMAN,4598.0,492.0,264.0,226.0,27.0,11.0,15,0.066372,ISMAEL ATENCIO,ISMAEL ATENCIO,POPULAR,15.0
2,PANAMÁ,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CE MONSEÑOR FRANCISCO BECKMAN,4598.0,492.0,264.0,226.0,27.0,11.0,14,0.061947,FRANCISCO EL MAESTRO MAURE,FRANCISCO EL MAESTRO MAURE,MOLIRENA,14.0
3,PANAMÁ,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CE MONSEÑOR FRANCISCO BECKMAN,4598.0,492.0,264.0,226.0,27.0,11.0,67,0.296460,ISMAEL ATENCIO,ISMAEL ATENCIO,PAN,67.0
4,PANAMÁ,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CE MONSEÑOR FRANCISCO BECKMAN,4598.0,492.0,264.0,226.0,27.0,11.0,72,0.318584,RUBÉN MEDINA,RUBÉN MEDINA,C.D.,72.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5970,PANAMÁ,8-9,2019.0,CAIMITILLO,ESC. PARARÁ PURU,4316.0,89.0,57.0,12.0,4.0,3.0,12,0.240000,JOSE LUIS GARCIA PALACIO,Jose Luis Garcia Palacio,C.D.,12.0
5971,PANAMÁ,8-9,2019.0,CAIMITILLO,ESC. PARARÁ PURU,4316.0,89.0,57.0,1.0,4.0,3.0,1,0.020000,LUIS CARLOS TREJOS ARIZA,Luis Carlos Trejos Ariza,VERDE,1.0
5972,PANAMÁ,8-9,2019.0,CAIMITILLO,ESC. PARARÁ PURU,4316.0,89.0,57.0,6.0,4.0,3.0,6,0.120000,RODOLFO PRECILLA CARRION,Rodolfo Precilla Carrion,MOLIRENA,6.0
5973,PANAMÁ,8-9,2019.0,CAIMITILLO,ESC. PARARÁ PURU,4316.0,89.0,57.0,2.0,4.0,3.0,2,0.040000,SONIA EDITH CUEVAS DE RUBIO,Sonia Edith Cuevas De Rubio,POPULAR,2.0
5974,PANAMÁ,8-9,2019.0,CAIMITILLO,ESC. PARARÁ PURU,4316.0,89.0,57.0,3.0,4.0,3.0,3,0.060000,TOMASITO LOPEZ RIVAS,Tomasito Lopez Rivas,ALIANZA,3.0

In [ ]:
dfr.drop(columns=['Candidato', 'Distrito'], inplace=True)

In [ ]:
dfr_win=dfr.groupby(['AÑO','Corregimiento','CANDIDATO'])[['votos']].sum()
dfr_win.sort_values(by=['AÑO','Corregimiento','votos'], ascending=False).head(50)

                                                                       votos
AÑO    Corregimiento          CANDIDATO
2019.0 LAS CUMBRES            ZAIDY QUINTERO                          5933.0
                              NOEL JESUS OVALLE                       3442.0
                              YADEL SUGEY MORALES FUENTES DE HERRERA  2593.0
                              JYMMY JAFET RODRIGUEZ VICTORIA           820.0
                              CARLOS ALFREDO SUCRE ABREGO              808.0
                              ARMANDO IVAN RIOS MARIAGA                622.0
                              MIRIAN ESTELA RIVAS MARTINEZ             307.0
                              ERIC OMAR DEL MAR MONTENEGRO             225.0
       ERNESTO CÓRDOBA CAMPOS RUBEN ARIEL MEDINA DOMINGUEZ            6176.0
                              LUIS ALEXANDER BARRIA MOSCOSO           4421.0
                              HERNAN CASTILLO SANCHEZ                 4276.0
                              ALCIBIADES CARRERA MENDOZA              2831.0
                              EDGAR JOEL RODRIGUEZ CONCEPCION         1937.0
                              ELSA EDITH GRINARD ROMERO               1721.0
                              JOSE AGUSTIN IGUALA SANCHEZ             1626.0
                              JOSE VICTOR CAICEDO ARBOLEDA             618.0
                              CELSO CUESTA MOSQUERA                    428.0
       CHILIBRE               YOIRA ENITH PEREA BERMUDEZ DE MORENO    5206.0
                              ALEYSIS UREÑA BARBA                     4579.0
                              VIDAL GARCÍA                            3522.0
                              JOSE OLDEMAR ORO MURILLO                1981.0
                              MELINA LIZBETH ROSALES                  1836.0
                              TOMAS GUILLERMO SOUSA ZEBALLOS           701.0
                              GUILLERMO ORLANDO CAMPOS BRUCE           380.0
                              ANTONIO ENRIQUE VASQUEZ AGUILAR          337.0
       CAIMITILLO             RODOLFO PRECILLA CARRION                2784.0
                              HECTOR RAUL CEDEÑO RODRIGUEZ            1709.0
                              ARIEL ALFREDO DE LEON REYES             1470.0
                              JOSE LUIS GARCIA PALACIO                 909.0
                              TOMASITO LOPEZ RIVAS                     828.0
                              ERIC ADOLFO TERAN CORNEJO                432.0
                              LUIS CARLOS TREJOS ARIZA                 325.0
                              BAUDILIO GONZALEZ JARAMILLO              301.0
                              SONIA EDITH CUEVAS DE RUBIO              232.0
       ALCALDE DÍAZ           RICARDO ALBERTO PRECILLA                8852.0
                              ADALBERTO TORRES CARRION                4146.0
                              INDIRA YARISELLY KWIERS PINEDA          2670.0
                              SOLMILANYI JUDITH CHAVEZ JAEN DE JAEN   1876.0
                              ANDRÉS ÁLVAREZ RUEDA                    1033.0
                              MIGUEL ALONSO MORALES MARTINEZ           868.0
                              HOMERO IVAN COPARROPA ESCLOPIS           793.0
                              CIRILO GOMEZ JARAMILLO                   344.0
                              CONCEPCION GOBEA ALVEO                   161.0
2014.0 LAS CUMBRES            ZAIDY QUINTERO                          3691.0
                              ALINA GONZÁLEZ CÓRDOBA                  3045.0
                              HILARIO RODRÍGUEZ                       2623.0
                              ADALIDES EL MAESTRO GÓNZALEZ            2087.0
                              HÉCTOR RAMPLA ARROCHA                    727.0
                              RUBÉN QUINTERO                           381.0
                              REINA LILIANA RIVERA                     183.0

In [ ]:
def ranking_corr(df): #Función para hacer el ranking por año
  df['AÑO-CORR'] = df['AÑO'].astype(str) + '-'+df['Corregimiento']
  years=df['AÑO-CORR'].unique()
  df1= df.head(0)
  for i in years:
    df['top_res']=df[df['AÑO-CORR'] == i]['votos'].rank(ascending=False)
    df1=df1.append(df)

  df1.dropna(inplace=True)
  return df1

In [ ]:
dfr_win.reset_index(inplace=True)
dfr_win=ranking_corr(dfr_win)

In [ ]:
dfr_win

,AÑO,Corregimiento,CANDIDATO,votos,AÑO-CORR,top_res
0,2009.0,CHILIBRE,CONCEPCIÓN CHÁVEZ,3303.0,2009.0-CHILIBRE,3.0
1,2009.0,CHILIBRE,EUGENIO D. RUIZ.P,118.0,2009.0-CHILIBRE,9.0
2,2009.0,CHILIBRE,GUADALUPE ILLUECA,204.0,2009.0-CHILIBRE,7.0
3,2009.0,CHILIBRE,IRVINGMANOLOCERVANTES,196.0,2009.0-CHILIBRE,8.0
4,2009.0,CHILIBRE,JOVANA DE PÉREZ,301.0,2009.0-CHILIBRE,6.0
...,...,...,...,...,...,...
80,2019.0,LAS CUMBRES,JYMMY JAFET RODRIGUEZ VICTORIA,820.0,2019.0-LAS CUMBRES,4.0
81,2019.0,LAS CUMBRES,MIRIAN ESTELA RIVAS MARTINEZ,307.0,2019.0-LAS CUMBRES,7.0
82,2019.0,LAS CUMBRES,NOEL JESUS OVALLE,3442.0,2019.0-LAS CUMBRES,2.0
83,2019.0,LAS CUMBRES,YADEL SUGEY MORALES FUENTES DE HERRERA,2593.0,2019.0-LAS CUMBRES,3.0
84,2019.0,LAS CUMBRES,ZAIDY QUINTERO,5933.0,2019.0-LAS CUMBRES,1.0

In [ ]:
dfr_win['top_res']=dfr_win['top_res'].apply(lambda x: 1 if x == 1 else 0)

In [ ]:
dfr_win.drop(columns=['votos'],inplace=True)

In [ ]:
dfr_win['key_win']=dfr_win['AÑO'].astype(str) +'-' + dfr_win['CANDIDATO']
dfr_win.set_index('key_win',inplace=True)
dfr['key_win']=dfr['AÑO'].astype(str) +'-' + dfr['CANDIDATO']

In [ ]:
dfr=dfr.join(dfr_win, on='key_win',lsuffix='l')
dfr.drop(columns=['CANDIDATOl','key_win'],inplace=True)

In [ ]:
dfr.isnull().sum()

Circuito              0
AÑOl                  0
Corregimientol        0
Centro                0
MESA                  0
ELECTORES             0
EMITIDOS              0
VALIDOS               0
BLANCOS               0
NULOS                 0
TOTALES               0
% MESA POR ESCUELA    0
Partido               0
votos                 0
AÑO                   0
Corregimiento         0
CANDIDATO             0
AÑO-CORR              0
top_res               0
dtype: int64

In [ ]:
wb=gc.open_by_key('1VPZ9Nha_BoDTPhX1-heXl0tkAy1kOU3tv8nOb3jWlFQ')
ws2=wb.worksheet('Sheet2')
#ws2.update([dfr.columns.tolist()] + dfr.values.tolist())

# Mesas y Votos emitidos Rep Correg

In [ ]:
cols_r=dfr.columns.to_list()

In [ ]:
cols_r

['Circuito',
 'AÑOl',
 'Corregimientol',
 'Centro',
 'MESA',
 'ELECTORES',
 'EMITIDOS',
 'VALIDOS',
 'BLANCOS',
 'NULOS',
 'TOTALES',
 '% MESA POR ESCUELA',
 'Partido',
 'votos',
 'AÑO',
 'Corregimiento',
 'CANDIDATO',
 'AÑO-CORR',
 'top_res']

In [ ]:
df_mesar

,Circuito,AÑOl,Corregimientol,Centro,MESA,ELECTORES,EMITIDOS,VALIDOS,BLANCOS,NULOS,TOTALES,% MESA POR ESCUELA,Partido,votos,AÑO
0,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CE MONSEÑOR FRANCISCO BECKMAN,4598.0,492.0,264.0,226.0,27.0,11.0,58,0.256637,P.R.D.,58.0,2014.0
1,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CE MONSEÑOR FRANCISCO BECKMAN,4598.0,492.0,264.0,226.0,27.0,11.0,15,0.066372,POPULAR,15.0,2014.0
2,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CE MONSEÑOR FRANCISCO BECKMAN,4598.0,492.0,264.0,226.0,27.0,11.0,14,0.061947,MOLIRENA,14.0,2014.0
3,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CE MONSEÑOR FRANCISCO BECKMAN,4598.0,492.0,264.0,226.0,27.0,11.0,67,0.296460,PAN,67.0,2014.0
4,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CE MONSEÑOR FRANCISCO BECKMAN,4598.0,492.0,264.0,226.0,27.0,11.0,72,0.318584,C.D.,72.0,2014.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5970,8-9,2019.0,CAIMITILLO,ESC. PARARÁ PURU,4316.0,89.0,57.0,12.0,4.0,3.0,12,0.240000,C.D.,12.0,2019.0
5971,8-9,2019.0,CAIMITILLO,ESC. PARARÁ PURU,4316.0,89.0,57.0,1.0,4.0,3.0,1,0.020000,VERDE,1.0,2019.0
5972,8-9,2019.0,CAIMITILLO,ESC. PARARÁ PURU,4316.0,89.0,57.0,6.0,4.0,3.0,6,0.120000,MOLIRENA,6.0,2019.0
5973,8-9,2019.0,CAIMITILLO,ESC. PARARÁ PURU,4316.0,89.0,57.0,2.0,4.0,3.0,2,0.040000,POPULAR,2.0,2019.0
5974,8-9,2019.0,CAIMITILLO,ESC. PARARÁ PURU,4316.0,89.0,57.0,3.0,4.0,3.0,3,0.060000,ALIANZA,3.0,2019.0

In [ ]:
df_mesar=dfr[cols_r[0:11]]
df_mesar['votos']=dfr['votos']
#df_mesar.groupby(['AÑOl','MESA'])[['ELECTORES']].mean()
df_mesar.drop(columns=['VALIDOS'],inplace=True)

df_mesar=df_mesar.groupby(df_mesar.columns.to_list()[0:-2])[['votos']].sum().sort_values(by=['AÑOl','MESA','votos'])
df_mesar.reset_index(inplace=True)


df_mesar.sort_values(by=['MESA'], inplace=True)
df_mesar.reset_index(inplace=True, drop=True)
#df_mesar

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
df_mesar.rename(columns={'AÑOl':'AÑO'},inplace=True)

In [ ]:
df_mesar

,Circuito,AÑO,Corregimientol,Centro,MESA,ELECTORES,EMITIDOS,BLANCOS,NULOS,votos
0,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3606.0,498.0,256.0,10.0,4.0,242.0
1,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3607.0,498.0,326.0,26.0,35.0,265.0
2,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3608.0,497.0,344.0,9.0,14.0,321.0
3,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3609.0,498.0,341.0,13.0,6.0,322.0
4,8-9,2019.0,CHILIBRE,ESC. BILINGÜE SANTOS JORGE,3610.0,496.0,357.0,8.0,7.0,342.0
...,...,...,...,...,...,...,...,...,...,...
835,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,ESC. REP. DE RUMANÍA,4662.0,458.0,372.0,5.0,2.0,365.0
836,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,ESC. REP. DE RUMANÍA,4663.0,457.0,372.0,10.0,9.0,353.0
837,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CASETA GAZEBO URB. QUINTAS DEL LAGO,4664.0,252.0,241.0,18.0,7.0,216.0
838,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,CASETA GAZEBO URB. VALLES DEL LAGO,4665.0,167.0,158.0,13.0,7.0,138.0
839,44782.0,2014.0,ERNESTO CÓRDOBA CAMPOS,C.E.F.A.C.E.I MIS PRIMEROS PASOS,4666.0,286.0,215.0,9.0,4.0,202.0

In [ ]:
wb_r=gc.open_by_key('1SCPq28XsLGloQbllu79r1Btp-cXDPSxDbq_T_603qMA')
ws_mr=wb_r.worksheet('Mesa_rep')
ws_mr.update([df_mesar.columns.tolist()] + df_mesar.values.tolist())

{'spreadsheetId': '1SCPq28XsLGloQbllu79r1Btp-cXDPSxDbq_T_603qMA',
 'updatedCells': 8410,
 'updatedColumns': 10,
 'updatedRange': 'Mesa_rep!A1:J841',
 'updatedRows': 841}